name: Nightly Test (NPU)
on:
  schedule:
    - cron: '0 18 * * *'  # Execute at 2:00 a.m. Beijing Time every day
  pull_request:
    branches:
      - main
      - testcases
    paths:
      - ".github/workflows/nightly-test-npu.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to test. If not provided, uses the default branch.'
        required: false
        type: string
        default: ''
      job_filter:
        description: 'Select which job to run (leave empty or "all" to run all jobs)'
        required: false
        type: string
        default: 'all'
      image_a3:
        description: 'The a3 running docker image of the test task.'
        required: false
        type: string
        default: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3'
      skip_install_flag:
        description: 'Indicates whether to skip the installation of sglang, defaulting to false.'
        required: false
        type: string
        default: 'true'
  workflow_call:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to test. If not provided, uses the default branch.'
        required: false
        type: string
        default: ''
      job_filter:
        description: 'Select which job to run (leave empty or "all" to run all jobs)'
        required: false
        type: string
        default: 'all'
      image_a3:
        description: 'The a3 running docker image of the test task.'
        required: false
        type: string
        default: ''
      skip_install_flag:
        description: 'Indicates whether to skip the installation of sglang, defaulting to false.'
        required: false
        type: string
        default: ''
concurrency:
  group: nightly-test-npu-${{ inputs.ref || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}
jobs:
  set-image-config:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-vars.outputs.ref }}
      job_filter: ${{ steps.set-vars.outputs.job_filter }}
      image_a3: ${{ steps.set-vars.outputs.image_a3 }}
      skip_install_flag: ${{ steps.set-vars.outputs.skip_install_flag }}
    steps:
      # When triggered by PR, no inputs parameters are used. The latest community code is tested by default.
      - name: Set image config
        id: set-vars
        run: |
          if [ -z "${{ inputs.ref }}" ]; then
            echo "ref=" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          fi
          if [ -z "${{ inputs.job_filter }}" ]; then
            echo "job_filter=all" >> $GITHUB_OUTPUT
          else
            echo "job_filter=${{ inputs.job_filter }}" >> $GITHUB_OUTPUT
          fi
          if [ -z "${{ inputs.image_a3 }}" ]; then
            echo "image_a3=swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3" >> $GITHUB_OUTPUT
          else
            echo "image_a3=${{ inputs.image_a3 }}" >> $GITHUB_OUTPUT
          fi
          if [ -z "${{ inputs.skip_install_flag }}" ]; then
            echo "skip_install_flag=false" >> $GITHUB_OUTPUT
          else
            echo "skip_install_flag=${{ inputs.skip_install_flag }}" >> $GITHUB_OUTPUT
          fi
  nightly-poc-single-node-tests:
    name: single-node-poc
    if: ${{ !cancelled() }}
    needs: [set-image-config]
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        test_config:
          # qwen3_6_35b_a3b performance tests
          # qwen3_32b performance tests
          - name: test_npu_qwen3_32b_w8a8_2p_in3k5_out1k5_50ms_a2
            runner: linux-aarch64-a3-4
            test_case: test/registered/ascend/performance/qwen3_32b/test_npu_qwen3_32b_w8a8_2p_in3k5_out1k5_50ms_a2.py
            test_type: 'perf'
          - name: qwen3_32b_bf16_8p_in18k_out4k_6ms_gpqa
            runner: linux-aarch64-a3-16
            test_case: test/registered/ascend/performance/qwen3_32b/test_npu_qwen3_32b_bf16_8p_in18k_out4k_6ms.py
            test_type: 'perf'
    uses: ./.github/workflows/nightly-test-npu-e2e-single-node.yml
    with:
      runner: ${{ matrix.test_config.runner }}
      test_type: ${{ matrix.test_config.test_type }}
      test_config_name: ${{ matrix.test_config.name }}
      test_case: ${{ matrix.test_config.test_case }}
      image: ${{ needs.set-image-config.outputs.image_a3 }}
      install_sglang_from_source: false
      transformers_version: ''

  check-all-jobs:
    needs:
      - nightly-poc-single-node-tests
    runs-on: ubuntu-latest
    container:
      image: docker.m.daocloud.io/ubuntu:22.04
    steps:
      - name: Check if any job failed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more nightly test jobs failed"
            exit 1
          fi
          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more nightly test jobs were cancelled"
            exit 1
          fi
          echo "All nightly test jobs passed"
